ALTER TABLE student_vms ADD COLUMN IF NOT EXISTS console_enabled BOOLEAN DEFAULT TRUE;
ALTER TABLE student_vms ADD COLUMN IF NOT EXISTS ssh_enabled BOOLEAN DEFAULT TRUE;
ALTER TABLE student_vms ADD COLUMN IF NOT EXISTS rdp_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE student_vms ADD COLUMN IF NOT EXISTS spice_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE student_vms ADD COLUMN IF NOT EXISTS assigned_ip VARCHAR(64);
ALTER TABLE student_vms ADD COLUMN IF NOT EXISTS default_username VARCHAR(100);
ALTER TABLE student_vms ADD COLUMN IF NOT EXISTS ssh_port INTEGER DEFAULT 22;
