import { useEffect, useState } from 'react'
import api from '../services/api'
import { listMyAssignments } from '../services/classroomApi'

export default function CreateVmPage({ setMessage }) {
  const [templates,setTemplates]=useState([])
  const [templateId,setTemplateId]=useState('')
  const [labName,setLabName]=useState('linuxlab')
  const [discoveredCount,setDiscoveredCount]=useState(0)
  const [availability,setAvailability]=useState([])
  const [assignments,setAssignments]=useState([])
  const [assignmentId,setAssignmentId]=useState('')
  useEffect(()=>{api.get('/templates').then(r=>{const rows = Array.isArray(r.data) ? r.data : []; setTemplates(rows); if(rows[0]) setTemplateId(rows[0].id)}).catch(()=>setTemplates([])); listMyAssignments().then(rows=>{setAssignments(rows||[]); const first=(rows||[]).find(row=>row.can_provision); if(first){setAssignmentId(String(first.id));setTemplateId(String(first.template_id));setLabName(first.lab_name||'classroom-lab')}}).catch(()=>setAssignments([])); api.get('/admin/proxmox/templates/discovered').then(r=>setDiscoveredCount(Array.isArray(r.data)?r.data.length:0)).catch(()=>setDiscoveredCount(0)); api.get('/admin/proxmox/templates/availability').then(r=>setAvailability(Array.isArray(r.data)?r.data:[])).catch(()=>setAvailability([]))},[])
  const usableAssignments=assignments.filter(row=>row.can_provision)
  const create=async()=>{try{const r=await api.post('/vms',{template_id:Number(templateId),assignment_id:assignmentId?Number(assignmentId):null,lab_name:labName,auto_start:true}); setMessage({type:'success',text:r.data.message||'Provisioning queued'}); if(assignmentId) setAssignments(rows=>rows.map(row=>String(row.id)===String(assignmentId)?{...row,can_provision:false,student_vm_id:r.data.id}:row))}catch(e){setMessage({type:'error',text:JSON.stringify(e?.response?.data?.detail||'Create failed')})}}
  const chooseAssignment=e=>{setAssignmentId(e.target.value);const assignment=assignments.find(row=>String(row.id)===e.target.value);if(assignment){setTemplateId(String(assignment.template_id));setLabName(assignment.lab_name||'classroom-lab')}}
  return <div className='panel'><h3>Create VM</h3><p style={{color:'#a7b0d6'}}>Students provision from an active classroom assignment. Instructors can provision directly from organization templates.</p>{assignments.length>0?<select className='input' value={assignmentId} onChange={chooseAssignment}><option value=''>Select available assignment…</option>{usableAssignments.map(row=><option key={row.id} value={row.id}>{row.run_name} — {row.lab_name} — {row.template_name}</option>)}</select>:null}<select className='input' value={templateId} disabled={!!assignmentId} onChange={e=>setTemplateId(e.target.value)}>{templates.map(t=><option key={t.id} value={t.id}>{t.name} (VMID {t.source_vmid}, {t.proxmox_node})</option>)}</select>{templates.length===0?<p className='muted'>No active classroom VM assignment is available. Ask your instructor to open a lab run and assign the roster.</p>:null}{templates.length===0 && discoveredCount>0?<p className='muted'>Proxmox templates exist but are not currently assigned through an active lab.</p>:null}{assignments.length>0 && usableAssignments.length===0?<p className='muted'>Your current assignments are already provisioned or outside their active schedule.</p>:null}{(() => { const a = availability.find(x => String(x.template_id) === String(templateId)); return a && !a.can_balance_across_all_nodes ? <p className='muted'>This template is currently available only on {a.available_nodes.join(', ')}. Load balancing will be limited. {a.recommended_action || ''}</p> : null })()}<input className='input' value={labName} onChange={e=>setLabName(e.target.value)} placeholder='Lab name' /><button onClick={create} disabled={!templateId || (assignments.length>0 && !assignmentId)}>Create VM</button></div>
}
