import { useEffect, useState } from 'react'
import api from '../services/api'

export default function DesktopPoolsPage({ setMessage }) {
  const [rows,setRows]=useState([])
  const [templates,setTemplates]=useState([])
  const [resourcePools,setResourcePools]=useState([])
  const [clusters,setClusters]=useState([])
  const [nodes,setNodes]=useState([])
  const [f,setF]=useState({name:'',description:'',pool_type:'lab',template_id:'',resource_pool_id:'',cluster_id:'',node_id:'',storage_pool:'',network_bridge:'',min_ready:0,max_desktops:20,auto_start:true,auto_recycle:false,naming_prefix:'lab',assignment_mode:'manual',is_active:true})
  const load=()=>{api.get('/admin/desktop-pools').then(r=>setRows(r.data));api.get('/admin/templates').then(r=>setTemplates(r.data));api.get('/admin/pools').then(r=>setResourcePools(r.data));api.get('/admin/proxmox/clusters').then(r=>setClusters(r.data));api.get('/admin/proxmox/nodes').then(r=>setNodes(r.data))}
  useEffect(()=>{load()},[])
  const create=async()=>{try{await api.post('/admin/desktop-pools',{...f,template_id:f.template_id?Number(f.template_id):null,resource_pool_id:f.resource_pool_id?Number(f.resource_pool_id):null,cluster_id:f.cluster_id?Number(f.cluster_id):null,node_id:f.node_id?Number(f.node_id):null,min_ready:Number(f.min_ready),max_desktops:Number(f.max_desktops)});setMessage({type:'success',text:'Desktop pool created'});load()}catch(e){setMessage({type:'error',text:JSON.stringify(e?.response?.data?.detail||'Failed')})}}
  return <section className='panel'><h2>Desktop Pools</h2><div className='group'><input className='input' placeholder='Name' value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><select className='input' value={f.pool_type} onChange={e=>setF({...f,pool_type:e.target.value})}><option>dedicated</option><option>shared</option><option>lab</option></select><select className='input' value={f.template_id} onChange={e=>setF({...f,template_id:e.target.value})}><option value=''>Template</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><select className='input' value={f.resource_pool_id} onChange={e=>setF({...f,resource_pool_id:e.target.value})}><option value=''>Resource Pool</option>{resourcePools.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select className='input' value={f.cluster_id} onChange={e=>setF({...f,cluster_id:e.target.value})}><option value=''>Cluster</option>{clusters.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select className='input' value={f.node_id} onChange={e=>setF({...f,node_id:e.target.value})}><option value=''>Node</option>{nodes.map(n=><option key={n.id} value={n.id}>{n.node_name}</option>)}</select><input className='input' placeholder='Min ready' value={f.min_ready} onChange={e=>setF({...f,min_ready:e.target.value})}/><input className='input' placeholder='Max desktops' value={f.max_desktops} onChange={e=>setF({...f,max_desktops:e.target.value})}/><select className='input' value={f.assignment_mode} onChange={e=>setF({...f,assignment_mode:e.target.value})}><option>manual</option><option>first_login</option><option>scheduled</option></select><button className='btn' onClick={create}>Create Desktop Pool</button></div><table className='table2'><thead><tr><th>Name</th><th>Type</th><th>Template</th><th>Resource Pool</th><th>Cluster</th><th>Node</th><th>Min Ready</th><th>Max</th><th>Assignment</th><th>Active</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.pool_type}</td><td>{r.template_id||'-'}</td><td>{r.resource_pool_id||'-'}</td><td>{r.cluster_id||'-'}</td><td>{r.node_id||'-'}</td><td>{r.min_ready}</td><td>{r.max_desktops}</td><td>{r.assignment_mode}</td><td>{String(r.is_active)}</td></tr>)}</tbody></table>{!rows.length?<p className='muted'>No desktop pools yet.</p>:null}</section>
}
