import { useEffect, useState } from 'react'
import api from '../services/api'

export default function PoolsPage({ setMessage }) {
  const [rows, setRows] = useState([])
  const [clusters, setClusters] = useState([])
  const [nodes, setNodes] = useState([])
  const [form, setForm] = useState({ name:'', description:'', enabled:true, default_template_id:'', max_vms:20, max_running_vms:10, auto_start:true, recycle_on_logout:false, cluster_id:'', node_id:'', storage_pool:'', network_bridge:'', placement_strategy:'any_enabled_node', preferred_node_id:'', resource_pool_id:'' })
  const load=()=>{api.get('/admin/pools').then(r=>setRows(r.data)).catch(()=>setRows([])); api.get('/admin/proxmox/clusters').then(r=>setClusters(r.data)).catch(()=>setClusters([])); api.get('/admin/proxmox/nodes').then(r=>setNodes(r.data)).catch(()=>setNodes([]))}
  useEffect(()=>{load()},[])
  const submit=async()=>{try{await api.post('/admin/pools',{...form,default_template_id:form.default_template_id?Number(form.default_template_id):null,cluster_id:form.cluster_id?Number(form.cluster_id):null,node_id:form.node_id?Number(form.node_id):null,preferred_node_id:form.preferred_node_id?Number(form.preferred_node_id):null,resource_pool_id:form.resource_pool_id?Number(form.resource_pool_id):null});setMessage({type:'success',text:'Pool created'});load()}catch(e){setMessage({type:'error',text:JSON.stringify(e?.response?.data?.detail||'Failed')})}}
  return <section className='panel'><h2>Resource Pools</h2><div className='group'><input className='input' placeholder='Name' value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input className='input' placeholder='Description' value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><select className='input' value={form.cluster_id} onChange={e=>setForm({...form,cluster_id:e.target.value})}><option value=''>Cluster</option>{clusters.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select className='input' value={form.node_id} onChange={e=>setForm({...form,node_id:e.target.value})}><option value=''>Node (optional)</option>{nodes.map(n=><option key={n.id} value={n.id}>{n.node_name}</option>)}</select><select className='input' value={form.placement_strategy} onChange={e=>setForm({...form,placement_strategy:e.target.value})}><option>fixed_node</option><option>any_enabled_node</option><option>least_running_vms</option><option>least_memory_usage</option><option>round_robin</option></select><input className='input' placeholder='Storage Pool' value={form.storage_pool} onChange={e=>setForm({...form,storage_pool:e.target.value})}/><input className='input' placeholder='Network Bridge' value={form.network_bridge} onChange={e=>setForm({...form,network_bridge:e.target.value})}/><button className='btn' onClick={submit}>Create Pool</button></div><table className='table2'><thead><tr><th>Name</th><th>Cluster</th><th>Node</th><th>Placement</th><th>Storage</th><th>Bridge</th><th>Enabled</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.cluster_id||'-'}</td><td>{r.node_id||'-'}</td><td>{r.placement_strategy||'-'}</td><td>{r.storage_pool||'-'}</td><td>{r.network_bridge||'-'}</td><td>{String(r.enabled)}</td></tr>)}</tbody></table></section>
}
