import { useEffect, useState } from 'react'
import api from '../services/api'

export default function UsersPage({ setMessage, user }) {
  const [users,setUsers]=useState([]); const [groups,setGroups]=useState([])
  const [form,setForm]=useState({username:'',email:'',display_name:'',role:'Student',password:''})
  const [groupName,setGroupName]=useState('')
  const load=()=>{api.get('/admin/users').then(r=>setUsers(r.data)); api.get('/admin/groups').then(r=>setGroups(r.data))}
  useEffect(()=>{load()},[])
  const createUser=async()=>{try{await api.post('/admin/users',form);setForm({username:'',email:'',display_name:'',role:'Student',password:''});load();setMessage({type:'success',text:'User created'})}catch(e){setMessage({type:'error',text:JSON.stringify(e?.response?.data?.detail||'Create failed')})}}
  const toggle=async(u)=>{try{await api.post(`/admin/users/${u.id}/${u.is_active?'disable':'enable'}`);load()}catch{setMessage({type:'error',text:'Update failed'})}}
  const del=async(u)=>{if(!confirm(`Delete ${u.username}?`))return; try{await api.delete(`/admin/users/${u.id}`);load()}catch(e){setMessage({type:'error',text:JSON.stringify(e?.response?.data?.detail||'Delete failed')})}}
  const createGroup=async()=>{try{await api.post('/admin/groups',{name:groupName});setGroupName('');load()}catch{setMessage({type:'error',text:'Group create failed'})}}
  return <section className='grid-2'><div className='panel'><h2>Users</h2><div className='group'><input className='input' placeholder='Username' value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/><input className='input' placeholder='Email' value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input className='input' placeholder='Display Name' value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})}/><input className='input' placeholder='Temp Password' type='password' value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><select className='input' value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option>Student</option><option>Teacher</option><option>Admin</option></select><button className='btn' onClick={createUser}>Add user</button></div><table className='table2'><thead><tr><th>User</th><th>Role</th><th>Active</th><th>Actions</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.username}<div className='muted'>{u.email}</div></td><td>{u.role}</td><td>{String(u.is_active)}</td><td className='group'><button className='btn ghost' disabled={u.id===user?.id} onClick={()=>toggle(u)}>{u.is_active?'Disable':'Enable'}</button><button className='btn danger' disabled={u.id===user?.id} onClick={()=>del(u)}>Delete</button></td></tr>)}</tbody></table></div><div className='panel'><h2>Groups</h2><div className='group'><input className='input' value={groupName} onChange={e=>setGroupName(e.target.value)} placeholder='New group'/><button className='btn' onClick={createGroup}>Create</button></div><table className='table2'><thead><tr><th>Name</th><th>Description</th><th>Members</th></tr></thead><tbody>{groups.map(g=><tr key={g.id}><td>{g.name}</td><td>{g.description||'-'}</td><td>{g.member_count||0}</td></tr>)}</tbody></table></div></section>
}
