import { useEffect, useState } from 'react'
import api from '../services/api'

const statusClass = (s) => `badge ${s==='running'?'badge-running':s==='stopped'?'badge-stopped':s==='provisioning'?'badge-provisioning':'badge-error'}`

export default function VmsPage({ setMessage }) {
  const [vms,setVms]=useState([])
  const [busy,setBusy]=useState({})
  const [selected,setSelected]=useState(null)
  const load=()=>api.get('/vms').then(r=>setVms(r.data))
  useEffect(()=>{load()},[])
  const act=async(vm,a)=>{setBusy(p=>({...p,[vm.id]:true})); try{if(a==='delete'){if(!confirm('Delete VM?')) return; await api.delete(`/vms/${vm.id}`)}else if(a==='status'){await api.get(`/vms/${vm.id}/status`)}else await api.post(`/vms/${vm.id}/${a}`); await load(); setMessage({type:'success',text:`${a} successful`})}catch(e){setMessage({type:'error',text:JSON.stringify(e?.response?.data?.detail||'Action failed')})} finally{setBusy(p=>({...p,[vm.id]:false}))}}
  const conn=async(vm,p)=>{try{const r=await api.get(`/vms/${vm.id}/console/${p}`); if(p==='ttyd'){window.open(r.data.url,'_blank')} if(p==='rdp'){const blob=new Blob([r.data.rdp_file||''],{type:'application/rdp'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`vm-${vm.vmid}.rdp`;a.click()} }catch(e){setMessage({type:'error',text:JSON.stringify(e?.response?.data?.detail||'Connect failed')})}}
  return <div className='panel'><h3>My VMs</h3><table className='vm-table'><thead><tr><th>Name</th><th>VMID</th><th>Status</th><th>Node</th><th>IP</th><th>Actions</th><th>Connect</th><th>Details</th></tr></thead><tbody>{vms.map(v=><tr key={v.id}><td>{v.vm_name}</td><td>{v.vmid}</td><td><span className={statusClass(v.status)}>{v.status}</span></td><td>{v.proxmox_node}</td><td>{v.assigned_ip||'-'}</td><td><div className='group'><button disabled={busy[v.id]} onClick={()=>act(v,'start')}>Start</button><button disabled={busy[v.id]} onClick={()=>act(v,'stop')}>Stop</button><button disabled={busy[v.id]} onClick={()=>act(v,'reboot')}>Reboot</button><button className='btn-danger' disabled={busy[v.id]} onClick={()=>act(v,'delete')}>Delete</button><button disabled={busy[v.id]} onClick={()=>act(v,'status')}>Refresh</button></div></td><td><div className='group'>{v.ssh_enabled&&v.assigned_ip?<button onClick={()=>conn(v,'ttyd')}>Web Terminal</button>:null}{v.console_enabled?<button onClick={()=>conn(v,'novnc')}>Console</button>:null}{v.rdp_enabled?<button onClick={()=>conn(v,'rdp')}>RDP</button>:null}{v.spice_enabled?<button onClick={()=>conn(v,'spice')}>SPICE</button>:null}</div></td><td><button onClick={()=>setSelected(v)}>View</button></td></tr>)}</tbody></table>{selected?<div className='vm-details panel'><h4>VM Details</h4><div>Name: {selected.vm_name}</div><div>Owner ID: {selected.owner_id}</div><div>Template ID: {selected.template_id}</div><div>Node: {selected.proxmox_node}</div><div>Status: <span className={statusClass(selected.status)}>{selected.status}</span></div><div>IP: {selected.assigned_ip||'-'}</div><div>Protocols: {[selected.console_enabled&&'console', selected.ssh_enabled&&'ssh', selected.rdp_enabled&&'rdp', selected.spice_enabled&&'spice'].filter(Boolean).join(', ')||'none'}</div></div>:null}</div>
}
