import React, { useEffect, useMemo, useState } from 'react'
import ReactDOM from 'react-dom/client'
import { BrowserRouter, Routes, Route, Link, Navigate, useNavigate } from 'react-router-dom'
import api from './api/client'

const card = { border: '1px solid #ddd', borderRadius: 8, padding: 12, minWidth: 160 }
const btn = { marginRight: 8, marginBottom: 6 }
const badgeColor = { running: '#198754', stopped: '#6c757d', error: '#dc3545', provisioning: '#ffc107' }

function Message({ message }) { return message ? <div style={{ padding: 10, color: message.type === 'error' ? '#dc3545' : '#198754' }}>{message.text}</div> : null }
function statusBadge(s){ return <span style={{background: badgeColor[s] || '#999', color:'#fff', padding:'2px 8px', borderRadius:12}}>{s}</span> }

function Login({ onLogin, setMessage }) { const [username,setU]=useState('alice'); const [password,setP]=useState('Password123!'); const submit=async(e)=>{e.preventDefault(); try{const {data}=await api.post('/auth/login',{username,password}); localStorage.setItem('token',data.access_token); setMessage({type:'success',text:'Login successful.'}); onLogin();}catch(err){setMessage({type:'error',text:err?.response?.data?.detail||'Login failed.'})}}; return <form onSubmit={submit}><h2>Login</h2><input value={username} onChange={e=>setU(e.target.value)} /><input type='password' value={password} onChange={e=>setP(e.target.value)} /><button>Login</button></form> }

function Nav({ setUser }) { const n=useNavigate(); const logout=()=>{localStorage.removeItem('token'); setUser(false); n('/');}; return <nav style={{display:'flex',gap:12,padding:'10px 0'}}><Link to='/'>Home</Link><Link to='/vms'>My VMs</Link><Link to='/create'>Create VM</Link><button onClick={logout}>Logout</button></nav> }

function Dashboard({ user }) { const [vms,setV]=useState([]); const [t,setT]=useState([]); useEffect(()=>{api.get('/vms').then(r=>setV(r.data)); api.get('/templates').then(r=>setT(r.data));},[]); const stats=useMemo(()=>({total:vms.length,running:vms.filter(x=>x.status==='running').length,stopped:vms.filter(x=>x.status==='stopped').length,templates:t.length}),[vms,t]); return <div><h2>{user.role} Dashboard</h2><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><div style={card}>Total VMs: {stats.total}</div><div style={card}>Running VMs: {stats.running}</div><div style={card}>Stopped VMs: {stats.stopped}</div><div style={card}>Available Templates: {stats.templates}</div></div></div> }

function VMs({ user, setMessage }) { const [vms,setV]=useState([]); const [busy,setBusy]=useState({}); const [filters,setF]=useState({username:'',status:'',template:'',node:''}); const [audits,setA]=useState([]); const load=async()=>{const params=user.role==='Student'?{}:Object.fromEntries(Object.entries(filters).filter(([,v])=>v)); const r=await api.get('/vms',{params}); setV(r.data)}; useEffect(()=>{load(); if(user.role!=='Student') api.get('/admin/audit-logs').then(r=>setA(r.data)).catch(()=>{});},[]); const poll=async(id)=>{for(let i=0;i<4;i++){await new Promise(r=>setTimeout(r,1500)); try{await api.get(`/vms/${id}/status`)}catch{}}}; const run=async(vm,action)=>{if(action==='delete'&&!confirm(`Delete VM ${vm.vm_name}?`)) return; setBusy(p=>({...p,[vm.id]:true})); try{if(action==='delete') await api.delete(`/vms/${vm.id}`); else if(action==='status') await api.get(`/vms/${vm.id}/status`); else {await api.post(`/vms/${vm.id}/${action}`); await poll(vm.id);} await load(); setMessage({type:'success',text:`${action} action completed for ${vm.vm_name}.`});}catch(err){setMessage({type:'error',text:err?.response?.data?.detail?.error || JSON.stringify(err?.response?.data?.detail || `${action} failed`)})} finally {setBusy(p=>({...p,[vm.id]:false}))}};
  return <div><h3>{user.role==='Student'?'My VMs':'All VMs'}</h3>{user.role!=='Student'&&<div style={{marginBottom:10}}><input placeholder='username' value={filters.username} onChange={e=>setF({...filters,username:e.target.value})}/><input placeholder='status' value={filters.status} onChange={e=>setF({...filters,status:e.target.value})}/><input placeholder='template id' value={filters.template} onChange={e=>setF({...filters,template:e.target.value})}/><input placeholder='node' value={filters.node} onChange={e=>setF({...filters,node:e.target.value})}/><button onClick={load}>Apply</button></div>}<table><thead><tr><th>VM Name</th><th>VMID</th><th>Status</th><th>Node</th><th>Created At</th><th>Actions</th></tr></thead><tbody>{vms.map(v=><tr key={v.id}><td>{v.vm_name}</td><td>{v.vmid}</td><td>{statusBadge(v.status)}</td><td>{v.proxmox_node}</td><td>{v.created_at || '-'}</td><td>{v.status!=='running'&&<button disabled={!!busy[v.id]} style={btn} onClick={()=>run(v,'start')}>Start</button>}{v.status!=='stopped'&&<button disabled={!!busy[v.id]} style={btn} onClick={()=>run(v,'stop')}>Stop</button>}{v.status!=='stopped'&&<button disabled={!!busy[v.id]} style={btn} onClick={()=>run(v,'reboot')}>Reboot</button>}<button disabled={!!busy[v.id]} style={btn} onClick={()=>run(v,'delete')}>Delete</button><button disabled={!!busy[v.id]} style={btn} onClick={()=>run(v,'status')}>Refresh Status</button></td></tr>)}</tbody></table>{user.role!=='Student'&&<details style={{marginTop:16}}><summary>Audit Logs</summary><pre>{JSON.stringify(audits,null,2)}</pre></details>}</div>
}

function CreateVM({ setMessage }){ const [templates,setT]=useState([]); const [templateId,setId]=useState(''); const [labName,setL]=useState('linuxlab'); const [busy,setBusy]=useState(false); useEffect(()=>{api.get('/templates').then(r=>{setT(r.data); if(r.data[0]) setId(r.data[0].id)})},[]); const create=async()=>{setBusy(true); try{const r=await api.post('/vms',{template_id:Number(templateId),lab_name:labName,auto_start:true}); setMessage({type:'success',text:r.data.message||'VM created successfully.'});}catch(err){setMessage({type:'error',text:err?.response?.data?.detail?.error || JSON.stringify(err?.response?.data?.detail||'Create VM failed.')})} finally{setBusy(false)}}; return <div><h3>Create VM</h3><select value={templateId} onChange={e=>setId(e.target.value)}>{templates.map(t=><option value={t.id} key={t.id}>{t.name} ({t.proxmox_node}:{t.source_vmid})</option>)}</select><input value={labName} onChange={e=>setL(e.target.value)} /><button disabled={busy} onClick={create}>Create</button></div> }

function Templates({user,setMessage}){ const [t,setT]=useState([]); const [form,setForm]=useState({name:'',proxmox_node:'',source_vmid:'',enabled:true}); if(user.role==='Student') return null; const load=()=>api.get('/admin/templates').then(r=>setT(r.data)); useEffect(()=>{load()},[]); const add=async()=>{try{await api.post('/admin/templates',{...form,source_vmid:Number(form.source_vmid)}); setMessage({type:'success',text:'Template added'}); load();}catch(e){setMessage({type:'error',text:'Template add failed'})}}; return <div><h3>Template Management</h3><input placeholder='name' onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder='node' onChange={e=>setForm({...form,proxmox_node:e.target.value})}/><input placeholder='vmid' onChange={e=>setForm({...form,source_vmid:e.target.value})}/><label><input type='checkbox' checked={form.enabled} onChange={e=>setForm({...form,enabled:e.target.checked})}/>Enabled</label><button onClick={add}>Add</button><pre>{JSON.stringify(t,null,2)}</pre></div> }

function App(){ const [user,setUser]=useState(null); const [message,setMessage]=useState(null); const load=()=>api.get('/auth/me').then(r=>setUser(r.data)).catch(()=>setUser(false)); useEffect(()=>{load()},[]); if(user===null) return <div>Loading...</div>; if(user===false) return <><Message message={message}/><Login onLogin={load} setMessage={setMessage}/></>; return <BrowserRouter><Nav setUser={setUser}/><Message message={message}/><Routes><Route path='/' element={<Dashboard user={user}/>} /><Route path='/vms' element={<VMs user={user} setMessage={setMessage}/>} /><Route path='/create' element={<CreateVM setMessage={setMessage}/>} /><Route path='/templates' element={<Templates user={user} setMessage={setMessage}/>} /><Route path='*' element={<Navigate to='/'/>}/></Routes></BrowserRouter> }
ReactDOM.createRoot(document.getElementById('root')).render(<App />)
