import React, { useEffect, useMemo, useState } from 'react'
import ReactDOM from 'react-dom/client'
import { BrowserRouter, Routes, Route, Link, Navigate, useNavigate } from 'react-router-dom'
import api from './api/client'

const btn = { marginRight: 8, marginBottom: 6 }
const badgeColor = { running: '#198754', stopped: '#6c757d', error: '#dc3545', provisioning: '#ffc107' }
const card = { border: '1px solid #ddd', borderRadius: 8, padding: 12, minWidth: 160 }

const Message = ({ message }) => message ? <div style={{ color: message.type === 'error' ? '#dc3545' : '#198754', padding: 8 }}>{message.text}</div> : null
const statusBadge = (s) => <span style={{ background: badgeColor[s] || '#777', color: '#fff', borderRadius: 10, padding: '2px 8px' }}>{s}</span>

function Login({ onLogin, setMessage }) { const [username,setU]=useState('alice'); const [password,setP]=useState('Password123!'); const submit=async(e)=>{e.preventDefault(); try{const {data}=await api.post('/auth/login',{username,password}); localStorage.setItem('token',data.access_token); setMessage({type:'success',text:'Login successful'}); onLogin();}catch(err){setMessage({type:'error',text:'Login failed'})}}; return <form onSubmit={submit}><h2>Login</h2><input value={username} onChange={e=>setU(e.target.value)}/><input type='password' value={password} onChange={e=>setP(e.target.value)}/><button>Login</button></form> }
function Nav({setUser}) { const n=useNavigate(); return <nav style={{display:'flex',gap:10,padding:'8px 0'}}><Link to='/'>Home</Link><Link to='/vms'>My VMs</Link><Link to='/create'>Create VM</Link><button onClick={()=>{localStorage.removeItem('token'); setUser(false); n('/')}}>Logout</button></nav> }

function Dashboard({user}) { const [vms,setV]=useState([]), [t,setT]=useState([]); useEffect(()=>{api.get('/vms').then(r=>setV(r.data)); api.get('/templates').then(r=>setT(r.data));},[]); const s=useMemo(()=>({total:vms.length,running:vms.filter(v=>v.status==='running').length,stopped:vms.filter(v=>v.status==='stopped').length,templates:t.length}),[vms,t]); return <div><h2>{user.role} Dashboard</h2><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><div style={card}>Total VMs: {s.total}</div><div style={card}>Running VMs: {s.running}</div><div style={card}>Stopped VMs: {s.stopped}</div><div style={card}>Available Templates: {s.templates}</div></div></div> }

function VmDetails({ vm, details, onClose, onRefreshNet, onConnect, loadingConnect }) {
  if (!vm) return null
  return <div style={{ position: 'fixed', right: 20, top: 60, background: '#fff', border: '1px solid #ddd', padding: 12, width: 420 }}>
    <h4>VM Details: {vm.vm_name}</h4>
    <div>Status: {statusBadge(vm.status)}</div>
    <div>Owner: {details?.owner || 'n/a'}</div><div>Template: {details?.template || vm.template_id || 'n/a'}</div>
    <div>Hostname: {details?.hostname || vm.hostname || 'n/a'}</div><div>IP: {details?.assigned_ip || vm.assigned_ip || 'n/a'}</div>
    <div>Uptime: {details?.uptime ?? 'n/a'}</div><div>CPU/RAM: n/a</div>
    <div style={{marginTop:8}}><button style={btn} onClick={onRefreshNet}>Refresh Network Info</button></div>
    <div><button style={btn} disabled={loadingConnect} onClick={()=>onConnect('novnc')}>Open Console</button><button style={btn} disabled={loadingConnect} onClick={()=>onConnect('ssh')}>SSH</button><button style={btn} disabled={loadingConnect} onClick={()=>onConnect('rdp')}>RDP</button><button style={btn} disabled={loadingConnect} onClick={()=>onConnect('spice')}>SPICE</button></div>
    <button onClick={onClose}>Close</button>
  </div>
}

function VMs({ user, setMessage }) { const [vms,setV]=useState([]), [busy,setBusy]=useState({}), [selected,setSelected]=useState(null), [details,setDetails]=useState(null), [loadingConnect,setLoadingConnect]=useState(false); const load=async()=>setV((await api.get('/vms')).data); useEffect(()=>{load()},[]); const poll=async(id)=>{for(let i=0;i<4;i++){await new Promise(r=>setTimeout(r,1200)); try{await api.get(`/vms/${id}/status`)}catch{}}};
  const run=async(vm,action)=>{if(action==='delete'&&!confirm('Delete VM?')) return; setBusy(p=>({...p,[vm.id]:true})); try{ if(action==='delete') await api.delete(`/vms/${vm.id}`); else if(action==='status') await api.get(`/vms/${vm.id}/status`); else { await api.post(`/vms/${vm.id}/${action}`); await poll(vm.id)}; await load(); setMessage({type:'success', text:`${action} successful`})} catch(e){setMessage({type:'error',text:JSON.stringify(e?.response?.data?.detail || 'Action failed')})} finally{setBusy(p=>({...p,[vm.id]:false}))}}
  const refreshNet=async(vm)=>{try{const r=await api.get(`/vms/${vm.id}/network`); setDetails(r.data); await load(); setMessage({type:'success',text:'Network info refreshed'})}catch(e){setMessage({type:'error',text:'Network refresh failed'})}}
  const connect=async(vm,type)=>{setLoadingConnect(true); try{const r=await api.get(`/vms/${vm.id}/console/${type}`); if(type==='novnc'){window.open(`/api/vms/${vm.id}/console/novnc`, '_blank')} else if(type==='spice'){const blob=new Blob([r.data.config||''],{type:'text/plain'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=`vm-${vm.vmid}.vv`; a.click()} else if(type==='rdp'){const blob=new Blob([r.data.rdp_file||''],{type:'application/rdp'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=`vm-${vm.vmid}.rdp`; a.click()} else {setMessage({type:'success',text:`SSH target: ${r.data.username}@${r.data.host}`})} setMessage({type:'success',text:`${type.toUpperCase()} launch prepared`})}catch(e){setMessage({type:'error',text:JSON.stringify(e?.response?.data?.detail || 'Connect failed')})} finally{setLoadingConnect(false)}}
  return <div><h3>My VMs</h3><table><thead><tr><th>VM Name</th><th>VMID</th><th>Status</th><th>Node</th><th>Created At</th><th>IP</th><th>Actions</th><th>Connect</th></tr></thead><tbody>{vms.map(v=><tr key={v.id}><td><button onClick={()=>{setSelected(v); setDetails(null)}}>{v.vm_name}</button></td><td>{v.vmid}</td><td>{statusBadge(v.status)}</td><td>{v.proxmox_node}</td><td>{v.created_at||'-'}</td><td>{v.assigned_ip||'-'}</td><td>{v.status!=='running'&&<button style={btn} disabled={!!busy[v.id]} onClick={()=>run(v,'start')}>Start</button>}{v.status!=='stopped'&&<button style={btn} disabled={!!busy[v.id]} onClick={()=>run(v,'stop')}>Stop</button>}{v.status!=='stopped'&&<button style={btn} disabled={!!busy[v.id]} onClick={()=>run(v,'reboot')}>Reboot</button>}<button style={btn} disabled={!!busy[v.id]} onClick={()=>run(v,'delete')}>Delete</button><button style={btn} disabled={!!busy[v.id]} onClick={()=>run(v,'status')}>Refresh</button></td><td><button style={btn} disabled={loadingConnect} onClick={()=>connect(v,'novnc')}>Open Console</button><button style={btn} disabled={loadingConnect} onClick={()=>connect(v,'ssh')}>SSH</button><button style={btn} disabled={loadingConnect} onClick={()=>connect(v,'rdp')}>RDP</button><button style={btn} disabled={loadingConnect} onClick={()=>connect(v,'spice')}>SPICE</button></td></tr>)}</tbody></table><VmDetails vm={selected} details={details} onClose={()=>setSelected(null)} onRefreshNet={()=>refreshNet(selected)} onConnect={(t)=>connect(selected,t)} loadingConnect={loadingConnect}/></div> }

function CreateVM({ setMessage }) { const [templates,setT]=useState([]),[templateId,setId]=useState(''),[lab,setLab]=useState('linuxlab'); useEffect(()=>{api.get('/templates').then(r=>{setT(r.data); if(r.data[0])setId(r.data[0].id)})},[]); const create=async()=>{try{const r=await api.post('/vms',{template_id:Number(templateId),lab_name:lab,auto_start:true}); setMessage({type:'success',text:r.data.message||'VM created'})}catch(e){setMessage({type:'error',text:JSON.stringify(e?.response?.data?.detail||'Create failed')})}}; return <div><h3>Create VM</h3><select value={templateId} onChange={e=>setId(e.target.value)}>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><input value={lab} onChange={e=>setLab(e.target.value)}/><button onClick={create}>Create</button></div> }

function App(){ const [user,setUser]=useState(null), [message,setMessage]=useState(null); const load=()=>api.get('/auth/me').then(r=>setUser(r.data)).catch(()=>setUser(false)); useEffect(()=>{load()},[]); if(user===null) return <div>Loading...</div>; if(user===false) return <><Message message={message}/><Login onLogin={load} setMessage={setMessage}/></>; return <BrowserRouter><Nav setUser={setUser}/><Message message={message}/><Routes><Route path='/' element={<Dashboard user={user}/>} /><Route path='/vms' element={<VMs user={user} setMessage={setMessage}/>} /><Route path='/create' element={<CreateVM setMessage={setMessage}/>} /><Route path='*' element={<Navigate to='/'/>}/></Routes></BrowserRouter> }

ReactDOM.createRoot(document.getElementById('root')).render(<App />)
